[pytest]
base_url = https://www.saucedemo.com/
pythonpath = .

markers = 
    api: API tests no browser
    ui: UI tests with browser

addopts =
    --browser=chromium
    --screenshot=only-on-failure
    --tracing=retain-on-failure
    --html=report.html
    --self-contained-html
    --strict-markers