[pytest]
base_url = https://www.saucedemo.com/

addopts =   --browser=chromium 
            --headed 
            ; --tracing=retain-on-failure
            ; --screenshot=on
            ; --video=retain-on-failure

